2024-05-29 14:01:48,141 INFO    MainThread:22620 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-29 14:01:48,142 INFO    MainThread:22620 [wandb_setup.py:_flush():76] Configure stats pid to 22620
2024-05-29 14:01:48,142 INFO    MainThread:22620 [wandb_setup.py:_flush():76] Loading settings from C:\Users\lukea\.config\wandb\settings
2024-05-29 14:01:48,143 INFO    MainThread:22620 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\MSc\0_Project\MSc_Project\wandb\settings
2024-05-29 14:01:48,143 INFO    MainThread:22620 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-29 14:01:48,143 INFO    MainThread:22620 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-29 14:01:48,143 INFO    MainThread:22620 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': 'g:\\my drive\\msc\\0_project\\msc_project\\main.py', 'program': 'g:\\my drive\\msc\\0_project\\msc_project\\main.py'}
2024-05-29 14:01:48,143 INFO    MainThread:22620 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-29 14:01:48,144 INFO    MainThread:22620 [wandb_init.py:_log_setup():521] Logging user logs to G:\My Drive\MSc\0_Project\MSc_Project\wandb\run-20240529_140148-dsdji3c6\logs\debug.log
2024-05-29 14:01:48,144 INFO    MainThread:22620 [wandb_init.py:_log_setup():522] Logging internal logs to G:\My Drive\MSc\0_Project\MSc_Project\wandb\run-20240529_140148-dsdji3c6\logs\debug-internal.log
2024-05-29 14:01:48,144 INFO    MainThread:22620 [wandb_init.py:init():561] calling init triggers
2024-05-29 14:01:48,145 INFO    MainThread:22620 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'architecture': 'SCAE', 'dataset': 'MNIST', 'epochs': 3, 'batch size': 32, 'v_th': 1, 'tau_m': 24. * msecond}
2024-05-29 14:01:48,145 INFO    MainThread:22620 [wandb_init.py:init():611] starting backend
2024-05-29 14:01:48,145 INFO    MainThread:22620 [wandb_init.py:init():615] setting up manager
2024-05-29 14:01:48,149 INFO    MainThread:22620 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-29 14:01:48,152 INFO    MainThread:22620 [wandb_init.py:init():623] backend started and connected
2024-05-29 14:01:48,163 INFO    MainThread:22620 [wandb_init.py:init():715] updated telemetry
2024-05-29 14:01:48,220 INFO    MainThread:22620 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-29 14:01:48,832 INFO    MainThread:22620 [wandb_run.py:_on_init():2357] communicating current version
2024-05-29 14:01:49,211 INFO    MainThread:22620 [wandb_run.py:_on_init():2366] got version response upgrade_message: "wandb version 0.17.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-05-29 14:01:49,211 INFO    MainThread:22620 [wandb_init.py:init():799] starting run threads in backend
2024-05-29 14:01:49,784 INFO    MainThread:22620 [wandb_run.py:_console_start():2335] atexit reg
2024-05-29 14:01:49,786 INFO    MainThread:22620 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-05-29 14:01:49,786 INFO    MainThread:22620 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-05-29 14:01:49,786 INFO    MainThread:22620 [wandb_run.py:_redirect():2280] Redirects installed.
2024-05-29 14:01:49,788 INFO    MainThread:22620 [wandb_init.py:init():842] run started, returning control to user process
2024-05-29 14:40:58,757 ERROR   MainThread:22620 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-05-29 14:40:58,757 ERROR   MainThread:22620 [internal_api.py:execute():374] {"errors":[{"message":"entity not found during upsertSweep","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2024-05-29 14:43:35,810 ERROR   MainThread:22620 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-05-29 14:43:35,811 ERROR   MainThread:22620 [internal_api.py:execute():374] {"errors":[{"message":"entity not found during upsertSweep","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2024-05-29 14:44:46,684 ERROR   MainThread:22620 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-05-29 14:44:46,684 ERROR   MainThread:22620 [internal_api.py:execute():374] {"errors":[{"message":"entity not found during upsertSweep","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2024-05-29 14:45:08,912 ERROR   MainThread:22620 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-05-29 14:45:08,913 ERROR   MainThread:22620 [internal_api.py:execute():374] {"errors":[{"message":"entity not found during upsertSweep","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2024-05-29 14:47:47,990 ERROR   MainThread:22620 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-05-29 14:47:47,991 ERROR   MainThread:22620 [internal_api.py:execute():374] {"errors":[{"message":"entity not found during upsertSweep","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
