2024-05-29 17:57:17,258 INFO    MainThread:30276 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-29 17:57:17,259 INFO    MainThread:30276 [wandb_setup.py:_flush():76] Configure stats pid to 30276
2024-05-29 17:57:17,259 INFO    MainThread:30276 [wandb_setup.py:_flush():76] Loading settings from C:\Users\lukea\.config\wandb\settings
2024-05-29 17:57:17,260 INFO    MainThread:30276 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\MSc\0_Project\MSc_Project\wandb\settings
2024-05-29 17:57:17,260 INFO    MainThread:30276 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'root_dir': 'G:\\My Drive\\MSc\\0_Project\\MSc_Project', 'entity': 'llalderson', 'project': 'pytorch-sweeps-demo', 'run_id': 'zgh6omna', 'sweep_id': '3geq21om', 'sweep_param_path': 'G:\\My Drive\\MSc\\0_Project\\MSc_Project\\wandb\\sweep-3geq21om\\config-zgh6omna.yaml'}
2024-05-29 17:57:17,260 INFO    MainThread:30276 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-29 17:57:17,260 INFO    MainThread:30276 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': 'G:\\My Drive\\MSc\\0_Project\\MSc_Project\\main.py', 'program': 'G:\\My Drive\\MSc\\0_Project\\MSc_Project\\main.py'}
2024-05-29 17:57:17,260 INFO    MainThread:30276 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-29 17:57:17,261 INFO    MainThread:30276 [wandb_init.py:_log_setup():521] Logging user logs to G:\My Drive\MSc\0_Project\MSc_Project\wandb\run-20240529_175717-zgh6omna\logs\debug.log
2024-05-29 17:57:17,261 INFO    MainThread:30276 [wandb_init.py:_log_setup():522] Logging internal logs to G:\My Drive\MSc\0_Project\MSc_Project\wandb\run-20240529_175717-zgh6omna\logs\debug-internal.log
2024-05-29 17:57:17,261 INFO    MainThread:30276 [wandb_init.py:init():561] calling init triggers
2024-05-29 17:57:17,261 INFO    MainThread:30276 [wandb_init.py:init():568] wandb.init called with sweep_config: {'bs': 64, 'epochs': 3, 'lr': 0.001}
config: {'program': 'main.py', 'method': 'grid', 'metric': {'name': 'final_test_loss', 'goal': 'minimize'}, 'parameters': {'bs': {'values': [64]}, 'lr': {'values': [0.001, 0.0001, 1e-05, 1e-06]}, 'epochs': {'value': 3}}}
2024-05-29 17:57:17,261 INFO    MainThread:30276 [wandb_init.py:init():611] starting backend
2024-05-29 17:57:17,262 INFO    MainThread:30276 [wandb_init.py:init():615] setting up manager
2024-05-29 17:57:17,272 INFO    MainThread:30276 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-29 17:57:17,275 INFO    MainThread:30276 [wandb_init.py:init():623] backend started and connected
2024-05-29 17:57:17,298 INFO    MainThread:30276 [wandb_run.py:_config_callback():1347] config_cb None None {'bs': 64, 'epochs': 3, 'lr': 0.001}
2024-05-29 17:57:17,299 INFO    MainThread:30276 [wandb_init.py:init():715] updated telemetry
2024-05-29 17:57:17,361 INFO    MainThread:30276 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-29 17:58:47,421 ERROR   MainThread:30276 [wandb_init.py:init():774] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-29 17:58:47,916 ERROR   MainThread:30276 [wandb_init.py:init():1199] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\sdk\wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\sdk\wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-29 17:58:48,920 WARNING MsgRouterThr:30276 [router.py:message_loop():77] message_loop has been closed
